### ISSUE TITLE
Not all files in artifactory folder displayed

### ISSUE THREAD

**Issue by Onke** [pivotalservices/artifactory-resource#31]
Hi,

maybe I got something wrong, but I expect to have every file in concourse. We have a folder in artifactory where different files are stored, like:
```
| - myRepository
    | - myFolder
        | - myArtifact_2018_xy.zip
        | - myArtifact_XYZ_2018_xy.zip
```
I would expect that the resource in concourse would display both ZIP files, but actually it only shows the myArtifact_XYZ_2018_xy.zip. My regex:
myArtifact_(?<version>.*?).zip

Is this an issue in the resource or am I doing something wrong?

Thanks
Onke

**Comment by lsilvapvt** [comment]
Hello @Onke , the behavior you are experiencing with the resource is expected. 
The resource code only returns the last version of the file in artifactory that matches the regular expression provided. 
There are some known issues with the regexp matching when letters and numbers are part of the version number, so the recommendation is to have the regex setup in a way that matches only the numeric part of the version in the file name.
You can take a look at this article for an example on how the resource works: https://github.com/pivotalservices/concourse-pipeline-samples/tree/master/pipelines/jfrog/artifactory-integration
Regards.
