### ISSUE TITLE
Feature: allow the artifactory path to be configure as a parameters on put and get

### ISSUE THREAD

**Issue by lsilvapvt** [pivotalservices/artifactory-resource#4]
Maybe allow the artifactory path to be configure as a parameters on put and get

**Comment by mborges-pivotal** [comment]
I've worked on it, but it doesn't seem to be viable since at get the resource 'check' script runs and it doesn't contain the parameters in the request body. We may want to run this by concourse engineering. 

http://concourse.ci/implementing-resources.html
